### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by kwame-wallace** [Azure-Samples/active-directory-xamarin-native-v2#10]
Visual Studio 2017.

-- Running the sample without modification: **UserDetailsClient.UWP** with Windows Mobile Emulator 10.0.**14393**.0 WVGA 4 inch 512MB causes the app to immediately crash with a Access Denied Native exception at the line:

"PCA = new PublicClientApplication(ClientID);"

Switching to the Mobile Emulator 10.0.**15063**.0 WVGA 4 inch 512MB  the sample works as expected.

-- Running the **UserDetailsClient.iOS** without modification, the user token is never cached. The line:

**AuthenticationResult ar =  await App.PCA.AcquireTokenSilentAsync(App.Scopes, App.PCA.Users.FirstOrDefault());**

Always results in **ar==null**. You must always log in to Microsoftr everytime you run the sample -> unlike the working "10.0.15063.0" UWP app.

Hope this helps!

**Comment by jmprieur** [comment]
This is fixed.
