### ISSUE TITLE
AcquireTokenInteractive Fails with Broker on iOS 13

### ISSUE THREAD

**Issue by DieselSoup** [Azure-Samples/active-directory-xamarin-native-v2#107]
Hello,

I've downloaded the sample project and tried the sign in with broker method from an iOS emulator. The emulator is running iOS 13.2. When I click the Sign in With Broker button, an error occurs at the line 112 in `MainPage.xaml.cs`:

`authResult = await App.PCA.AcquireTokenInteractive(App.Scopes)
                                                      .WithParentActivityOrWindow(App.ParentWindow)
                                                      .WithUseEmbeddedWebView(true)
                                                      .ExecuteAsync();`

The exception message is:

`-canOpenURL: failed for URL: "msauthv2://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"`

Any idea why this may be happening? This issue does not occur on Android.

**Comment by jennyf19** [comment]
@DieselSoup is broker installed on the emulator? MSAL is trying to open the broker but it's not finding it. Also, broker is not available on android yet.

**Comment by DieselSoup** [comment]
@jennyf19 to answer your question, no the broker is not installed on the emulator. I'm looking into getting it installed. However, from what I understand, I should be able to query a broker without it being installed.

**Comment by bgavrilMS** [comment]
@DieselSoup  - we found a bug around this scenario - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1598

The expected behavior is for MSAL to redirect to an installation of the broker experience. 

I propose we close this bug and follow up on MSAL.

**Comment by jennyf19** [comment]
@bgavrilMS this is a different scenario, not related to the bug above.

**Comment by jennyf19** [comment]
@DieselSoup are you still having the issue with the latest version (4.13)?

**Comment by jennyf19** [comment]
closing, as this may be fixed w/more recent releases. @DieselSoup please reopen or open another one if you have issues. thank you.
