### ISSUE TITLE
Cannot get Android to complete login process

### ISSUE THREAD

**Issue by ThaineNorris** [Azure-Samples/active-directory-xamarin-native-v2#108]
I have integrated the code from this sample into my Xamarin.Forms app. I have configured Azure according to my best understanding of the documentation, and have made a painstaking emulation of the sample code, including the BrowserTabActivity XML block in the AndroidManifest. 

The end result is that it works perfectly on UWP. I am able to login and make other Microsoft graph calls, so I know the Azure configuration is correct, at least for UWP.

However, I cannot get it to work with Android. It goes through the login process all the way to the last step in authentication, which is the dialog that says, "Are you trying to log in to {my app name}?" The process stalls there. The dialog will neither continue, nor cancel. If I tap the continue button rapidly, then I get an error that too many authentication attempts have been made, so I know that it is communicating with Azure.

If I change the sample app ClientID to mine, it also works on UWP, but on Android I get the same problem that I am seeing in my app. It seems that would suggest an Azure configuration problem. But why does it work on UWP? How can one even have different configurations per platform for a "Desktop + Devices" app registration? Are there some extra Android-specific settings that need to be made somewhere?

Is there any way you could share the Azure app configuration manifest for this sample (redacted of course) so I could compare it to mine?

Any help would be greatly appreciated.

**Comment by TiagoBrenck** [comment]
I think the problem might be in the android manifest. VS latest XamarinForms template includes a package attribute in the manifest. You can remove that attribute to make the code work as is.

The problem is basically the redirect URL. With the package attribute, your app will have a different schema, thus a different redirect URL must be used.

We have a task planned to update this sample and cover this scenario.

Let us know if it worked for you.

**Comment by ThaineNorris** [comment]
Yes! That was the problem. Thank you for your help.

Comparing the Android manifest between the same code and my new VS project, I found the line you're referring to which looks like this:

    <application android:label="{myAppName}.Android"></application>

Removing this line fixed the login issue.

Hooray!

**Comment by TiagoBrenck** [comment]
Awesome! We will soon update the sample to use the most recent VS code template. I will keep this issue opened for now.

**Comment by papafe** [comment]
I have exactly the same issue, but I am just using the sample project here (without broker). I also can't go further the screen with "Are you trying to sign in to ...", and I have tried with both the default ClientID and RedirectUri, and my own, with the same results.
I am not sure if it makes a difference, but I am using Visual Studio for Mac in order to run the project

**Comment by joemicmc** [comment]
I'm also seeing the same problem with latest from master. I cloned repo and built without changing any of the client ids. UWP works no problems and you can sign in and your profile info is displayed. When running on Android (emulator or hardware) the process stalls at the point mentioned in this issue e.g.

> Are you trying to sign in to PublicClientSample? Cancel. Continue.

In the `AndroidManifest.xml` I have left the `package` attribute as is, as it matches the namespace for `MainActivity.cs`.

```<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="UserDetailsClient.Droid">
  <uses-sdk android:minSdkVersion="16" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <application>
    
  </application>
</manifest>```

Do you have any suggestions for what might be wrong here? Thanks! 😄

**Comment by TiagoBrenck** [comment]
Have you run this sample before? If so, it is also recommended to delete the existing app installation and re-install it.

**Comment by TiagoBrenck** [comment]
@joemicmc @JoeYim I found a mismatch of appId in `App.cs` vs `MsalActivity.cs`. I fixed it and opened a PR.

**Comment by joemicmc** [comment]
Thanks @TiagoBrenck! I realise now if I had followed the optional steps in the readme I would have discovered the issue... 😊
