### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by javedk** [Azure-Samples/active-directory-xamarin-native-v2#11]
The only the changes made to the sample app that ApplicationId is used mine but when run it and clicked Signin Microsoft dialog open for authentication input username and password clicked signin it redirect back to app with nothing no error nothing happen and tried to debug it but after below line executes breakpoint never hit.
  AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, App.UiParent);

**Comment by mtbgithub** [comment]
Similar issue, as outlined in [https://stackoverflow.com/questions/49083179/cannot-get-response-from-app-pca-acquiretokenasync-call-using-msal](stackoverflow).  Basically, while I can get your sample to work, I cannot port the code successfully into my own xamarin app.  I was wondering if it might have something to do with my using a shared project and you using a portable - though I can't understand why that should be.

**Comment by jmprieur** [comment]
@mtbgithub:
- do you have repro steps?
- we've added a Troubleshooting section in the README.md (among other improvements)
