### ISSUE TITLE
AppReg Portal cant enter msal redirect uri

### ISSUE THREAD

**Issue by jherman330** [Azure-Samples/active-directory-xamarin-native-v2#110]
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/1-Basic

When following optional steps to create your own app reg in your own tenant step 6 says the following

6. In the list of pages for the app, select Authentication..
In the Redirect URIs | Suggested Redirect URIs for public clients (mobile, desktop) section, check the option of the form msal<clientId>://auth

The portal validation prevents you from saving your changes as it doesn't like the format of the msal. 

![image](https://user-images.githubusercontent.com/5427763/70559417-9806b280-1b54-11ea-81b2-fcdd7a1241bf.png)

the hacky work around is to edit the manifest and hand enter the msal string

![image](https://user-images.githubusercontent.com/5427763/70559505-c6848d80-1b54-11ea-8508-07ca2c6a23ea.png)

**Comment by TiagoBrenck** [comment]
Thanks for reporting @jherman330 . We will redirect this bug to AzurePortal team. 
I confirmed that this behavior is only happening when you use the **try the new experience** option.

**Comment by jennyf19** [comment]
any update on this @TiagoBrenck ?

**Comment by mmacy** [comment]
Within **App registrations (Preview)**, select your application, then **Authentication** > **Try out the new experience**.

![image](https://user-images.githubusercontent.com/13394541/73024037-93831a00-3de1-11ea-861f-36827c715f0a.png)

Then select **Add a platform** > **Mobile and desktop applications**

![image](https://user-images.githubusercontent.com/13394541/73024065-a72e8080-3de1-11ea-970d-af793e595633.png)

Select the `msal11111111-1111-1111-1111-111111111111://auth` option, then select **Configure**.

![image](https://user-images.githubusercontent.com/13394541/73024497-8ca8d700-3de2-11ea-8a68-569ca5e8a598.png)

At this point, you should see the properly formatted redirect URI in the portal.

![image](https://user-images.githubusercontent.com/13394541/73024294-2754e600-3de2-11ea-8665-5619afc85eab.png)

**Comment by TiagoBrenck** [comment]
They have fixed the bug, so we can close this.

**Comment by jennyf19** [comment]
@jherman330 this has been fixed. thanks for opening the issue.
