### ISSUE TITLE
README.md is not correct

### ISSUE THREAD

**Issue by papafe** [Azure-Samples/active-directory-xamarin-native-v2#111]
The README.md file has a Step 3 ("Configure the Visual Studio project with your app coordinates"), that is indicated as being optional, while actually it is mandatory. 

If users do not follow this step, then they will not insert the ClientID in the correct parts in the iOS and Android code.

**Comment by jmprieur** [comment]
Thanks @papafe for the feedback.
If you do optional step 2, then indeed Step 3 is not optional.
I wonder how we can explain this.

cc: @jennyf19 @TiagoBrenck

**Comment by papafe** [comment]
@jmprieur Actually you need to do Step 3 in any case. 
For example, in the Android code for `MsalActivity.cs`,  there is still a placeholder for ClientID instead of the actual test value:

```
namespace UserDetailsClient.Droid
{
    [Activity]
    [IntentFilter(new[] { Intent.ActionView },
        Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
        DataHost = "auth",
        DataScheme = "msal[ClientID]")]
    public class MsalActivity : BrowserTabActivity
    {
    }
}
```

**Comment by TiagoBrenck** [comment]
I ve opened a PR to fix it. Since we have a sample appId, I added it in the configuration files instead of having `[ClientID]` mask.

**Comment by jennyf19** [comment]
closing as fixed
