### ISSUE TITLE
Single Sign-Out

### ISSUE THREAD

**Issue by GhimpuLucianEduard** [Azure-Samples/active-directory-xamarin-native-v2#122]
Hello,

I'm having a hard time figuring out if it's possible to sign out a user that initially signed in using Azure AD App Registration.

The sign-in is used in a Xamarin.Forms mobile app. 

The sample from here says that a simple call to **IPublicClientApplication.RemoveAsync(account)** is enough. While it's true, this works for the scenario where a single user uses the device.

I'm wondering if it's possible to sign out the user completely (from office 365 or from anywhere is signed in).

This is an issue for me in the following scenario:

1. User A signs in the mobile app
2. User A access outlook in the mobile browser
3. User A signs out form the mobile app BUT he is still signed in the browser.
4. User B takes the device to sign in but at the same time, he can see all user A emails since he was not signed out from the browser.  

I tried to just do an HTTP GET to **https://login.microsoftonline.com/{tenantID}/oauth2/logout**
but doesn't seem to work (I've also configured the Logout URL to **https://login.microsoftonline.com/{tenantID}/oauth2/logout** in the Azure AD App.

**Comment by GhimpuLucianEduard** [comment]
I'm closing this issue since it seems to be a duplicate of https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/86. 

As far as I understand there is an ongoing effort to provide such feature. In the meantime, I will try clearing the cookies. If there is a better solution to this issue, please feel free to reply.

**Comment by Coder-RKV** [comment]
@GhimpuLucianEduard were you able to clear cookies?
