### ISSUE TITLE
Could not find any available provisioning profiles for UserDetailsClientiOS on iOS.	

### ISSUE THREAD

**Issue by ClayAchahui** [Azure-Samples/active-directory-xamarin-native-v2#123]
Hello, i downloaded the basic sample project, android run succesfully; but in ios not.
error: 
`Could not find any available provisioning profiles for UserDetailsClientiOS on iOS.`

Im using Iphone 8 iOS 13.3 on visual studio 2019 with local connected mac.

**Comment by TiagoBrenck** [comment]
Did you follow one of theses provisioning configurations listes in this doc?
https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/

**Comment by ClayAchahui** [comment]
Thanks for response! I have a problem: I don't have a real device. Can i run on simulator iOS?

**Comment by TiagoBrenck** [comment]
Yes, you can run it on simulator. However, Visual Studio must be connected to a MAC

**Comment by ClayAchahui** [comment]
**Overview**
I have a visual studio 2019 connected with MAC on red. 
Xcode has a developer account and certificate as iOS development.(if i don't have a iOS device, do i need a profile provisioning? because to create profile provisioning it ask me a device iOS).

Some where i noticed that i need create a xcode project to pair with visual estudio project(bundle identifier). I don't know if this is necesary or not.

In visual studio i don't have idea how settings on iOS project because a lot of projects that i checked    they were differents.

I've been looking for a sample that show configuration on visual studio for windows connected with MAC using iOS simulator. Sorry for my english and i'm so confused with this.

**Comment by TiagoBrenck** [comment]
Would [this steps](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/94#issuecomment-507865146) help? I basically wrote them when I was configuring my Xamarin setup for the first time.

About your question, you do need profile provisioning for simulator. The physical device requirement is not necessary.

**Comment by ClayAchahui** [comment]
Your guide is usefull; but it the 5 step doesn't work [https://stackoverflow.com/questions/39603667/failed-to-create-provisioning-profile](failed to create provisioning profile).
in your guide says "xcode will automatically generate a profile for you" on the other hand on stackoverflow say "it is not necesary for simulator..."

**Comment by TiagoBrenck** [comment]
The official docs for this can be found [here](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows). That Stackoverflow question is related to xcode only, not Xamarin. The integration between Xamarin and Xcode is another topic. Also, don't mix Xamarin iOS simulator vs xcode iOS simulator.

**Comment by ClayAchahui** [comment]
So... _the next step in iOS development is to provision your iOS device_ I need a device...?

**Comment by TiagoBrenck** [comment]
You do not need a device. Please go through the documentation. There is even a tutorial that has the print screen of the simulator.

https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/introduction-to-xamarin-ios-for-visual-studio

**Comment by ClayAchahui** [comment]
**automatic provisioning**
![image](https://user-images.githubusercontent.com/43356162/74884589-86563e00-5341-11ea-98d5-b4dd58e24e74.png)
![image](https://user-images.githubusercontent.com/43356162/74884693-c1587180-5341-11ea-8216-16bf712769ad.png)
**manual provisioning**
![image](https://user-images.githubusercontent.com/43356162/74884766-eb119880-5341-11ea-838b-58aa32c4d793.png)

**Comment by TiagoBrenck** [comment]
Did you also follow [this readme step](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/1-Basic#ios-specific-considerations) about the `Entitlements.plist`?

**Comment by ClayAchahui** [comment]
![image](https://user-images.githubusercontent.com/43356162/74886209-85271000-5345-11ea-891b-7693ff77aa83.png)
![image](https://user-images.githubusercontent.com/43356162/74886244-9bcd6700-5345-11ea-8ea4-19083c099cfd.png)
![image](https://user-images.githubusercontent.com/43356162/74886290-b3a4eb00-5345-11ea-8bf6-03ea8f05ed33.png)

**Comment by jennyf19** [comment]
@ClayAchahui you need to update the bundleId in the `Info.plist` to use your own:
This is the one for the sample:
`com.yourcompany.UserDetailsClient`

Try using your own BundleId and see if that resolves the issue.

**Comment by ClayAchahui** [comment]
Yeah, it is updated:
![image](https://user-images.githubusercontent.com/43356162/74939828-85afbd00-53be-11ea-90a5-af153507f0e4.png)

**Comment by jennyf19** [comment]
@ClayAchahui and you've signed in with your AppleId or CloudId in XCode? 
It looks like when you do automatic provisioning, you have an error:
![image](https://user-images.githubusercontent.com/19942418/74959067-cb6c8580-53be-11ea-85b8-cf4a9a7abf0f.png)

**Comment by ClayAchahui** [comment]
Works!
I have to register a device iOS and it works it. :D

**Comment by jennyf19** [comment]
@ClayAchahui yay!! great news. :shipit:

**Comment by ClayAchahui** [comment]
mmm without register a device... how can i do it? My tiny question.

**Comment by jennyf19** [comment]
@ClayAchahui what error are you getting now?

**Comment by ClayAchahui** [comment]
I'm not good with my english; but i'm going to explain it:

I'm a new in xamarin, here mi coworkers don't know about xamarin, i'm a first... So they said that to use MSAL i need a register a device iOS and other coworker said that iOS simulator was necessay, not a device. I tried it without device,only with simulator; but i didn't find a sample using visual studio for windows connected with MAC without register a device on apple account. Now is working on visual studio with simulator but i have to register a device on apple account.

My app is working but i still have doubts.

Thanks for all. <3

**Comment by jennyf19** [comment]
@ClayAchahui sounds good. glad it's working. let us know if you run into any other issues.

**Comment by shyammani** [comment]
> mmm without register a device... how can i do it? My tiny question.

For strange reasons, the final remedy to run iOS app on simulator, in case you are getting these errors.

1. Just register any IPhone available with you, as a device in apple developer (https://developer.apple.com/account/resources/devices/list).

And automatic provisioning will get completed successfully, then you can run your app on simulator.

**Comment by jennyf19** [comment]
Thanks for the insight @shyammani

**Comment by kgbuddhima** [comment]
Issue solved after install a provisioning profile for the bundleId
