### ISSUE TITLE
Msal xamarin form after login, ask again for authentication multiple times

### ISSUE THREAD

**Issue by elcaytuiro** [Azure-Samples/active-directory-xamarin-native-v2#124]
I Have a xamarin forms application with MSAL authentication with Office 365.  My App have multiple activities, y followed all steps showed in the sample project. 

I have tested the application on Android and IOS, but the application after User logged successful show again login page multiple time. After the third time the application load correctly. 

MSAL VERSION >  Microsoft.Identity 4.8.1
Xamarin forms 4.40.001640

Please help me.

**Comment by jennyf19** [comment]
@elcaytuiro Thanks for opening an issue here. Could you provide [logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging)?

also, have you tried running this sample as-is, but with your app settings (client_id, redirect_uri, etc)?

**Comment by jennyf19** [comment]
@elcaytuiro closing, as no response and unable to repro. Please let us know if you still see this behavior, or reopen the issue. Thank you.
