### ISSUE TITLE
Missing Microsoft.Identity.Client package in UserDetailsClient.iOS project

### ISSUE THREAD

**Issue by dsurrao** [Azure-Samples/active-directory-xamarin-native-v2#126]
I had to manually add the NuGet package **Microsoft.Identity.Client** to the **UserDetailsClient.iOS** project. 

Should this not automatically happen since the package is already defined as a dependency in the **UserDetailsClient** Xamarin project?

**Comment by jmprieur** [comment]
this should @dsurrao : but the same happened to me last time. There seem to be a tooling (Visual Studio/Nuget with Xamarin) issue.

**Comment by jennyf19** [comment]
@dsurrao closing, as external to MSAL. Please reopen or open another issue if necessary.
