### ISSUE TITLE
Android offers duplicate options when following the tutorial to change client id

### ISSUE THREAD

**Issue by hypervtechnics** [Azure-Samples/active-directory-xamarin-native-v2#127]
In the tutorial you add an entry to the AndroidManifest.xml *and* as an attribute to the MsalActivity. When the developer changed the ClientId during the tutorial this won't be the case. In the tutorial you do not mention the Entry in the AndroidManifest.xml in the part where the developer registers his own app in Azure. Therefore the data scheme will only apply to the sample one.

Just found https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1094 and #93. I just wanted to point out this specific symptom.

**Comment by jennyf19** [comment]
@jmprieur this is fixed now correct?
