### ISSUE TITLE
This Sample works great except for when Intune is implemented.

### ISSUE THREAD

**Issue by WesleyEvanMiller** [Azure-Samples/active-directory-xamarin-native-v2#130]
I want to use this code to authenticate an iOS Xamarin Forms application with Azure to make a simple REST call to app proxy. It works as expected except when I integrate the Intune SDK with my application. When I add the following line:

`IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount(identity);`

It hangs on the "Taking you to your organization's sign in page" page. The url is login.mircosoftonline.us. I am not sure if this is a bug or known conflict that can't be solved, but any help is appreciated. I am using these docs for the Intune SDK:

https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin

**Comment by jmprieur** [comment]
@WesleyEvanMiller : did you use the https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/2-With-broker sub folder?

**Comment by WesleyEvanMiller** [comment]
I have tried both. When I try to use the Broker method with the SDK (or rather that line above), it never even takes me to the authenticator.

**Comment by WesleyEvanMiller** [comment]
Wow. It looks like the Intune SDK package just needed to be updated to version 12.2.0 in my iOS project.
