### ISSUE TITLE
Compile Error: Could not find any available provisioning profiles for UserDetailsClientiOS on iOS (when using iOS Simulators)

### ISSUE THREAD

**Issue by JPhilC** [Azure-Samples/active-directory-xamarin-native-v2#132]
Hi all,

I realise that the error "Could not find provisioning profiles for " has been asked before and closed. I am asking again because other than a MacBookPro which I bought for Xamarin development I do not own an Apple device and it appears to be impossible to create a provisioning profile without having a device registered in my Apple Developer account. Is this the case or am I missing something?

The solutions offered in the other issue do not fully address the problem of working purely using the iOS simulators.

Thanks,

Phil

**Comment by jennyf19** [comment]
Hi @JPhilC - Will this [documentation](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/no-codesigning-keys#how-to-fix) work for you?

**Comment by jennyf19** [comment]
@JPhilC any update? please reopen if you need assistance (and tag me)...thank you.
