### ISSUE TITLE
Sample uses ancient Xamarin.Forms dependencies and package config

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-xamarin-native-v2#135]
If you create a new Xamarin Forms project, it is massively different from what this sample shows. 

We should move all the logic from this sample into new csproj files to benefit from all the Xamarin upgrades. 

The problems with this old version: 

- uses package.config, which provides sub-par experience in MSAL, as it shows APIs which we normally hide if you use <packageRefernce>
- automatic migration of package.config is broken

**Comment by bgavrilMS** [comment]
@pmahend1 - apologies for not picking up on your PR, we need to do better on samples. I believe @jmprieur also did this work now

**Comment by pmahend1** [comment]
@bgavrilMS So my PR is no longer needed now? Did he make PackageReference changes as well?

**Comment by bgavrilMS** [comment]
No, you are right, your work does some more stuff. Any chance you can rebase your PR ?

**Comment by pmahend1** [comment]
@bgavrilMS sure. I am in the process of resolving conflicts and rebasing. I can't add reviewers, so if you can add that's really helpful

**Comment by pmahend1** [comment]
@bgavrilMS Done with rebasing and conflict resolution. Please add reviewers and proceed with review.

**Comment by bgavrilMS** [comment]
Thanks @pmahend1 - this has been merged, much appreciated!
