### ISSUE TITLE
Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication

### ISSUE THREAD

**Issue by bozhiqian** [Azure-Samples/active-directory-xamarin-native-v2#14]
I use Marshmallow (6.0.0) API Levele 23 with VS2017 emulator for Android. No Chrome has been installed.
When I run it, I got exception.

```
03-03 16:47:32.108 E/mono    ( 2338): Unhandled Exception:
03-03 16:47:32.108 E/mono    ( 2338): Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication
03-03 16:47:32.108 E/mono    ( 2338):   at (wrapper dynamic-method) System.Object:a768d874-5b11-4a24-afea-0e24259bf690 (intptr,intptr)
03-03 16:47:32.108 E/mono    ( 2338): 	ErrorCode: chrome_not_installed
03-03 16:47:32.109 E/mono-rt ( 2338): [ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication
03-03 16:47:32.109 E/mono-rt ( 2338):   at (wrapper dynamic-method) System.Object:a768d874-5b11-4a24-afea-0e24259bf690 (intptr,intptr)
03-03 16:47:32.109 E/mono-rt ( 2338): 	ErrorCode: chrome_not_installed
```
This is the same exception that I run it in my another sample xamarin app. 
Refer to [Custom tabs without Chrome problem](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/225)

**Comment by jmprieur** [comment]
This is expected for devices that don't support Chrome or Chrome custom tabs.  It's a lapse in the MSAL preview for both Xamarin and Android native.  

you can work around this by downloading Chrome. Please look at this help article for getting Chrome on a test emulator: https://github.com/Azure-Samples/active-directory-general-docs/blob/master/AndroidEmulator.md
