### ISSUE TITLE
SSO in Android using browser cookie sharing not working

### ISSUE THREAD

**Issue by SravanthiKare** [Azure-Samples/active-directory-xamarin-native-v2#146]
As given in documentation, we have tried configuring SSO by using system browser option. But, it seems it's not working. Can you please suggest what am i missing?

```

App.PCA = PublicClientApplicationBuilder.Create(B2CConstants.ClientID)
                    .WithRedirectUri($"msal{B2CConstants.ClientID}://auth")
                    .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                    .WithParentActivityOrWindow(()=>App.ParentWindow)
                    .WithAuthority(new Uri(B2CConstants.Authority))
                    .Build();

AuthResult = await App.PCA.AcquireTokenInteractive(B2CConstants.Scopes).WithAccount(LoginHelper.GetUserByPolicy(await App.PCA.GetAccountsAsync(), B2CConstants.PolicySignUpSignIn)).WithUseEmbeddedWebView(false).WithParentActivityOrWindow(App.ParentWindow).ExecuteAsync(); 
```

By default, MSAL is supposed to use system browser and share cookies for SSO. I have built 2 apps with same values. But SSO doesnt seem to work. Please help me on this regard.

**Comment by jmprieur** [comment]
@aiwangmicrosoft @trwalke @neha-bhargava @bgavrilMS 
FYI

**Comment by jmprieur** [comment]
@SravanthiKare : Did you try the scenario with broker?

**Comment by SravanthiKare** [comment]
@jmprieur  No, i didnt try moving broker option as we have decided to do with system browser option.

**Comment by bgavrilMS** [comment]
When you say that SSO isn't working, what do you mean? Are users requested to relogin every time? And since this is B2C, what users are you talking about - local users or external IDP users (which ones?)

**Comment by bgavrilMS** [comment]
MSAL does not control the browser experience, so we might need to open a ticket to the B2C service folks.

**Comment by SravanthiKare** [comment]
> When you say that SSO isn't working, what do you mean? Are users requested to relogin every time? And since this is B2C, what users are you talking about - local users or external IDP users (which ones?)

I meant SSO through cookie sharing using system browser. Following the same approach described in below references for SSO through System Browser.

https://developer.microsoft.com/en-us/identity/blogs/microsoft-authentication-libraries-for-android-ios-and-macos-are-now-generally-available/

https://docs.microsoft.com/en-us/azure/active-directory/develop/authorization-agents

**Comment by jmprieur** [comment]
@SravanthiKare : the recommendation is to use the broker from now.

**Comment by SravanthiKare** [comment]
@jmprieur 
Thanks.
