### ISSUE TITLE
AcquireTokenSilent not working after few mintunes in ios and anroid giving error

### ISSUE THREAD

**Issue by viveknegi51288** [Azure-Samples/active-directory-xamarin-native-v2#147]
Initially, application opening  a login page, after entering the credentials, I am able to receive the token. Once application closed and suddenly open its getting token sliently by using below method:
 authResult = await App.PCA.AcquireTokenSilent(App.Scopes, firstAccount).ExecuteAsync();

But after 15-20 min , when trying to open the application its again prompting for login screen.
Please help.

Android : - Android behaving weird,AcquireTokenSilent sometimes getting proper result, but sometime getting "Broker response returned error: Failed to acquire token sliently from the broker. IN order to perform brokered authentication on android you need to ensure that you have installed either Intune company portal(5.0.4789.0 or greater) or Microsoft Authenticator (6.2001.01400 or greater).

But I have already installed both above application. 

PLEASE HELP

**Comment by viveknegi51288** [comment]
Please help
@aiwangmicrosoft @trwalke @neha-bhargava  @bgavrilMS

**Comment by bgavrilMS** [comment]
Hi @viveknegi51288 - please log a bug on MSAL and provide logs so that we can investigate. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
