### ISSUE TITLE
[Question] Do we need the Powershell scripts?

### ISSUE THREAD

**Issue by pmahend1** [Azure-Samples/active-directory-xamarin-native-v2#148]
Do I need to have [Powreshell Folder 1](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/1-Basic/AppCreationScripts) or 

[Powershell Folder 2](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/2-With-broker/AppCreationScripts) if I am trying to connect Xamarin app through MSAL?

**Comment by jmprieur** [comment]
There are 2 scenarios @pmahend1 : please read the README.md.
- Basic (without brokers)
- With brokers
the powershell scripts to use depend on the scenario

But you probably rather want to follow the instructions in the README.md?

**Comment by pmahend1** [comment]
@jmprieur thanks for answering.I found out that in my case applications are already created in Azure , so I dont need to run these scripts. I will just have to call APIs to authenticate and get tokens
