### ISSUE TITLE
UWP Reply URL Incorrect

### ISSUE THREAD

**Issue by patrick-robin** [Azure-Samples/active-directory-xamarin-native-v2#149]
Following the instructions for the Basic sample configured for a single tenant I get the following error when authenticating within the UWP "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application".

To get the application to work I had to add a new redirect uri to my app registration with the uri: _ms-app://xxxxxxx_. Am I missing a step in the configuration somewhere or has there been a change in the implementation that means the documentation needs to be updated?

**Comment by aiwangmicrosoft** [comment]
Hi Patrick, in the sample I'm seeing [step #6 at this link](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/master/1-Basic#register-the-client-app-active-directory-xamarin-native-v2) suggest selecting the redirect URI of form msal<clientId>://auth. Is that the one you set?

**Comment by patrick-robin** [comment]
Yep, that's set and it's working for the Android app, however in the UserDetailsClient\App.cs class the constructor takes a parameter _specialRedirectUri_ which is used as the redirect uri when setting up the public client.

`public App(string specialRedirectUri = null)
        {
            PCA = PublicClientApplicationBuilder.Create(ClientID).WithTenantId("4a5378f9-29f4-4d3e-be89-669d03ada9d8")
                .WithRedirectUri(specialRedirectUri?? $"msal{ClientID}://auth")
                .WithIosKeychainSecurityGroup("com.microsoft.adalcache")
                .Build();

            MainPage = new NavigationPage(new UserDetailsClient.MainPage());
        }`

And in the UWP _MainPage.xaml.cs_  you have this:

`public MainPage()
        {
            this.InitializeComponent();

            // To get SSO with a UWP app, you'll need to register the following
            // redirect URI for your application
            Uri redirectURI = Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri();
            
            // Then use the following:
            LoadApplication(new UserDetailsClient.App(redirectURI.AbsoluteUri));
        }`

Which now I've read the comments in the code you need to add the app url as redirect uri in Azure, it might be worth adding it to the documentation as either an optional step or under the platform specific considerations.

**Comment by aiwangmicrosoft** [comment]
Yes, we can add that to the docs. Does it work for you now?

**Comment by saf-itpro** [comment]
@aiwangmicrosoft I am getting a similar error posted on `github` [here](https://github.com/OneDrive/onedrive-community-samples/issues/13). Could you please help?

**Comment by bgavrilMS** [comment]
Curerntly you need to set the redirect uri to "https://sso" and MSAL will internally switch to use `Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri();`

You do not need to register "https://sso" but you do need to register `WebAuthenticationBroker.GetCurrentApplicationCallbackUri()`

We have [a work item ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1901) to improve this experience - please vote for it. 

I also added more details in our wiki: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/UWP-specifics#make-the-browser-remember-previous-usernames

**Comment by amirvenus** [comment]
> Curerntly you need to set the redirect uri to "https://sso" and MSAL will internally switch to use `Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri();`
> 
> You do not need to register "https://sso" but you do need to register `WebAuthenticationBroker.GetCurrentApplicationCallbackUri()`
> 
> We have [a work item ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1901) to improve this experience - please vote for it.
> 
> I also added more details in our wiki:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/UWP-specifics#make-the-browser-remember-previous-usernames

Does that really need to be added in the UWP MainPage.xaml.cs?

I am getting an error:

'App' does not contain a constructor that takes 1 arguments. Would I have to change the constructor in App.xaml.cs file in the main project? I am confused how to pass that https://sso !

**Comment by bgavrilMS** [comment]
This is where you construct the `PublicClientApplication` object https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/master/1-Basic/UserDetailsClient/UserDetailsClient/App.cs#L22

Make sure that the redirect uri is "https://sso" and see if that works.

**Comment by amirvenus** [comment]
> This is where you construct the `PublicClientApplication` object https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/master/1-Basic/UserDetailsClient/UserDetailsClient/App.cs#L22
> 
> Make sure that the redirect uri is "https://sso" and see if that works.

Nope it's the same error :-(

**Comment by bgavrilMS** [comment]
I am not sure what the error is, but `'App' does not contain a constructor that takes 1 arguments` sounds like a compilation error which you should be able to figure out.

**Comment by amirvenus** [comment]
> I am not sure what the error is, but `'App' does not contain a constructor that takes 1 arguments` sounds like a compilation error which you should be able to figure out.

This is what I keep on getting:

![image](https://user-images.githubusercontent.com/5879559/102254178-3a900900-3f00-11eb-80c5-c815a8c913f1.png)

**Comment by jmprieur** [comment]
@amirvenus , now that MSAL.NET supports, WAM, you probably want to use it?
Please check out the latest version of the sample (.WithBroker) and https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam

**Comment by amirvenus** [comment]
> @amirvenus , now that MSAL.NET supports, WAM, you probably want to use it?
> Please check out the latest version of the sample (.WithBroker) and https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam

Sounds promising, but I don't know how to use it in a UWP app within Xamarin.Forms. 
Is there any sample repo I can test?

**Comment by jmprieur** [comment]
This is this sample, @amirvenus : it was updated.

See
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/bbedea6307fb2f93204fa522c3cd2b176ed6c137/2-With-broker/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs#L42-L53

https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/bbedea6307fb2f93204fa522c3cd2b176ed6c137/2-With-broker/UserDetailsClient/UserDetailsClient.UWP/MainPage.xaml.cs#L25-L28

**Comment by amirvenus** [comment]
> This is this sample, @amirvenus : it was updated.
> 
> See
> 
> https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/bbedea6307fb2f93204fa522c3cd2b176ed6c137/2-With-broker/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs#L42-L53
> 
> https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/bbedea6307fb2f93204fa522c3cd2b176ed6c137/2-With-broker/UserDetailsClient/UserDetailsClient.UWP/MainPage.xaml.cs#L25-L28

Thanks! 
I think I am getting there. I could get rid of that error and could get a token but apparently I cannot use that token to call any of my API endpoints as I keep on getting 401.
This is my code:

```
     var builder = PublicClientApplicationBuilder
                .Create(B2CConstants.ClientID);

            switch (Device.RuntimePlatform)
            {
                case Device.UWP:
                    builder = builder
                        .WithExperimentalFeatures()
                        //.WithB2CAuthority(B2CConstants.AuthoritySignInSignUp)
                        ;
                    builder.WithDefaultRedirectUri();
                    break;
                default:
                    builder = builder.WithB2CAuthority(B2CConstants.AuthoritySignInSignUp)
                        .WithIosKeychainSecurityGroup(B2CConstants.IOSKeyChainGroup)
                        .WithRedirectUri($"msal{B2CConstants.ClientID}://auth");
                    break;
            }
             
            PublicClientApplicationBuilder.Create(B2CConstants.ClientID);
```

When I uncomment `WithB2CAuthority(B2CConstants.AuthoritySignInSignUp) `, that previous error comes back.

**Comment by amirvenus** [comment]
And when I use WithBroker:

```
                    builder = PublicClientApplicationBuilder
                        .Create(B2CConstants.ClientID)
                        
                        .WithExperimentalFeatures()
                        .WithDefaultRedirectUri()
                        .WithB2CAuthority(B2CConstants.AuthoritySignInSignUp)
                        //.WithRedirectUri($"msal{B2CConstants.ClientID}://auth")
                        //.WithRedirectUri($"https://sso")
                        .WithBroker(true)
```

I get this screen:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/5879559/102468952-13455300-404a-11eb-8468-9bfe4b01b65f.png">

**Comment by jmprieur** [comment]
@amirvenus : sorry I had not understood you were targetting B2C. 
- This sample is for Azure AD, not for Azure AD B2C. you cannot use WAM with B2C.
- The B2C sample is https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

**Comment by jmprieur** [comment]
Proposing to close this issue. Feel free to open a new issue in the b2C-xamarin sample if you have one.
