### ISSUE TITLE
[UWP] We can't connect to the service you need right now. Check your network connection or try this again later.

### ISSUE THREAD

**Issue by amirvenus** [Azure-Samples/active-directory-xamarin-native-v2#152]
Hi,

I have tried the sample on iOS and Android and they work beautifully fine however, we would love to have the same for our UWP target inside the Xamarin.Forms project.

I do see the login pop, can enter my username and password and it even asks whether to remember me or not but right after that,I keep on getting the error:

![image](https://user-images.githubusercontent.com/5879559/90474485-48ce4400-e11d-11ea-8fb0-59880c4db0cf.png)

I have also tried the 'registry key' trick as well as setting the capabilities as prescribed on some forums and discussions:

But it's still the same..

```
  <Capabilities>
    <Capability Name="internetClient" />
    <uap:Capability Name="enterpriseAuthentication"/>
    <Capability Name="privateNetworkClientServer"/>
    <uap:Capability Name="sharedUserCertificates"/>
    <uap:Capability Name="userAccountInformation"/>
    <Capability Name="internetClientServer"/>
  </Capabilities>

```
Please advise

Thanks!

**Comment by jennyf19** [comment]
@amirvenus do you have fiddler or a proxy running? That will cause this error to appear.

**Comment by trwalke** [comment]
PLease provide more info and reopen @amirvenus

**Comment by amirvenus** [comment]
> @amirvenus do you have fiddler or a proxy running? That will cause this error to appear.

No, I don't have a fiddler or proxy. 

I am developing on a Windows VM (using Parallels on Mac)

**Comment by jennyf19** [comment]
@amirvenus thanks for the info. I'm not able to repro the issue. Can you share your code or provide a link to it?

**Comment by amirvenus** [comment]
> @amirvenus thanks for the info. I'm not able to repro the issue. Can you share your code or provide a link to it?

Shall I email it to you? It contains some confidential information...

**Comment by jennyf19** [comment]
@jennyf19 that works. i can also use our test credentials, so you can take your info out. jeferrie@microsoft.com

**Comment by bgavrilMS** [comment]
Hi - what is your redirect uri? 
Can you have a look at some troubleshooting we have for UWP https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-uwp-considerations?

**Comment by jennyf19** [comment]
closing. @amirvenus feel free to reopen w/more info for @bgavrilMS  to investigate.
