### ISSUE TITLE
Running below code on android breaks with exception, should the exclusivity be ignored automatically on android ?

### ISSUE THREAD

**Issue by kberawala** [Azure-Samples/active-directory-xamarin-native-v2#168]
Running below code on android breaks with exception, should the exclusivity be ignored automatically on android ?

![image](https://user-images.githubusercontent.com/13636878/119773766-78a84480-bf04-11eb-9f25-7b011404c67e.png)
![image](https://user-images.githubusercontent.com/13636878/119773818-89f15100-bf04-11eb-9f30-39d497130520.png)

_Originally posted by @kberawala in https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/114#issuecomment-849348808_

**Comment by jmprieur** [comment]
See https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/114#issuecomment-849348808
