### ISSUE TITLE
MSAL Redirect URI contains Client ID static in the manifest

### ISSUE THREAD

**Issue by filmar25** [Azure-Samples/active-directory-xamarin-native-v2#172]
Hello,

I have implemented MSAL for our Xamarin application (Android & iOS).

All working fine, but my problem is the Redirect URI. Actually, I'm using our own Azure Active Directory to develop and test. I created App Registration and configure Enterprise applications, so I have the ClientID for the application that is actually used in the Redirect URI.

But our application is designed to be used by differents enterprises that have their own Azure Active Directory. So they will create App Registration and Enterprise Applications in their Azure Active Directory. The ClientID will be different.

If I well understand, the URL Scheme is defined in the manifest of the application and cannot be change at runtime ?

So I am a little stock here and I didn't found the way to make Redirect URL dynamic by customer.

Can you help me please ?

Thank you for your help !

**Comment by filmar25** [comment]
Hi,

Finally, I misunderstand of the concept.

I can put everything I want in the URI.

Thank you !

**Comment by jmprieur** [comment]
@filmar25 : you can for a desktop app (not a web app), and provided what you choose is the same in the app-registration and your code.
