### ISSUE TITLE
AcquireTokenAsync never returns

### ISSUE THREAD

**Issue by paulelong** [Azure-Samples/active-directory-xamarin-native-v2#18]
I'm writing and app that needs to write a file on OneDrive.  I have this working on UWP, but on Android, it presents the authentication and I enter username/pw and it displays the "Let this app access your info" page."  I press Yes, and nothing happens.  The debugger never returns from AcquireTokenAsync, unless I hit the back button.   Neither YES/NO do anything.  Also I can't be sure the OnActivityResult is being touched, as a breakpoint there doesn't hit.  However, BPs in the OnCreate don't get hit either, so I'm not sure if there's a problem setting BPs in MainActivty.cs and debug on device.

I attempted the same steps with this example, and see the exact same behavior.  My code is derived from this example.  

Could it be a problem with my device (I only have one, galaxy s8).  Anything I could try?

**Comment by jmprieur** [comment]
@paulelong : can you try to set a breakpoint explicitly by calling `System.Diagnostics.Debugger.Break();`

**Comment by paulelong** [comment]
I've added the statement to OnActivityResult, and it only breaks when I close the page.  If I try Yes or No, it doesn't break into the debugger.  BTW, the only other change I made to your example was to use my ClientID, which I believe should be fine since it works in the UWP case with my app.

**Comment by jennyf19** [comment]
@paulelong - I just tested the sample using a Plus One and a Nexus phone, and was able to log-in successfully on both. 
Which redirect URI are you using for the Android app?
Check out this info on the [redirectUri](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications), scroll down to the section on "For public client appplications developers using MSAL.NET"

**Comment by paulelong** [comment]
I believe that means there's something different about my s8's configuration that is causing an issue.  I don't have another device to test.  I could try the android emulator, but for me it's not even starting.  Is it worth trying to test on the emulator?

I read the page, and tried the variation mentioned there.  Below are the 3 versions:
* 1st the one that is in the project shows me a page that "We are unable to complete your request".  I assume that's because it's not my ID?
* 2nd, is using my ID, and it produces the issue above.
* 3rd, is using what I could understand from the article.  It also returns the "We are unable to complete your request."  The example given in the doc is com.microsoft.identity.client.sample, but I'm not sure if that has to be based on the app name, or is generic for this library?  Am I doing it right?

            //App.PCA.RedirectUri = "msala7d8cef0-4145-49b2-a91d-95c54051fa3f://auth";
            //App.PCA.RedirectUri = "msal3e78afa9-7c5c-4fb2-a4f0-8ac58725fea0://auth";
            App.PCA.RedirectUri = "msal3e78afa9-7c5c-4fb2-a4f0-8ac58725fea0://com.microsoft.identity.client.sample";

Thanks so much for your help so far.   I'm flailing a bit, but I don't yet understand a good way to make progress to understand the next step, assuming it's specific to my device.

**Comment by jennyf19** [comment]
@paulelong Do you have Chrome or Chrome Custom Tabs installed on the device? Xamarin Android in MSAL can only launch Chrome or Chrome Custom Tabs.

**Comment by paulelong** [comment]
Chrome is installed on my s8, though Edge is the default browser.  When the dialog appears the interface that appears shows "Powered by Chrome" in the menu under the options "Find in page, Add to Home Screen, Desktop site, Open in Edge".  So I think that means it's running Chrome or Chrome Custom Tabs, but to be honest it's not obvious.

**Comment by jennyf19** [comment]
Thanks for the update. Sounds like you have Chrome, so this is not the reason for the issue you are seeing. 
The sample is preconfigured...could you try cloning the repo, building and deploying without changing any of the configuration? And let us know what happens?

**Comment by paulelong** [comment]
Cloning the project to a new directory worked.  Working backwards, I now see my stupid mistake.  In the article, it says msal[APPLICATIONID], so I entered msal[3e78afa9-7c5c-4fb2-a4f0-8ac58725fea0] rather than msal3e78afa9-7c5c-4fb2-a4f0-8ac58725fea0, and that caused the problem.  

I'm guess my original project that had the problem was because I didn't change all 3 places of the clientID and the mismatch causes this same behavior.

Not sure if there's some way to make it easier to help users find this type of issue, but at least I got things working.  I really appreciate the help!

**Comment by jennyf19** [comment]
@paulelong - Great success! Glad you got it working. Thanks for the feedback and update. 

re: @jmprieur

**Comment by cmw9706** [comment]
I feel I am having a similar problem using ADAL.
My OnActivityResult is getting hit but my AcquireTokenAsync is never returning an AuthorizationResult?

**Comment by jennyf19** [comment]
@cmw9706 Which version of ADAL are you using?

**Comment by cmw9706** [comment]
@jennyf19 4.5.1 

I have verified that this will work in a new project but something about my project seems to be causing this?

I followed the documentation to a T and so I opened an issue

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1541

**Comment by jennyf19** [comment]
@cmw9706 thanks. will take a look and get back to you in the issue you opened.
