### ISSUE TITLE
Can't Sign in - Please use the / Organizations or tenant - specific endpoint.

### ISSUE THREAD

**Issue by hernandoz** [Azure-Samples/active-directory-xamarin-native-v2#22]
Hi , I am getting an error .. 
"Sorry but we're having trouble with signing you in 
AADSTS90130: Application "APLICATION ID" (MY APP ) is not supported over the / common or / consumers endpoints. Please use the / Organizations or tenant - specific endpoint."

How/where can I add the Organizations or tenant - specific endpoint.? 

Thanks for your help

**Comment by hernandoz** [comment]
sorry I forgot to mention the app runs ok and I can enter my WORK account all working the error is after processing my details . Thanks

**Comment by jmprieur** [comment]
you would have to update this line to also pass the authority as https://login.microsoftonline.com/organizations/

for more details, see
See [public client application](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#publicclientapplication)
