### ISSUE TITLE
Token cache is not persisted on iOS

### ISSUE THREAD

**Issue by Eldin66** [Azure-Samples/active-directory-xamarin-native-v2#23]
Currently, the user that logged in does not get stored in any way. So this part in OnAppearing never gets executed successfully, because there are no users: 
`var ar = await App.PCA.AcquireTokenSilentAsync(App.Scopes, App.PCA.Users.FirstOrDefault());`

Is there any way to persist the logged in user? So that the user does not have to relog every time the application closes and opens.

**Comment by jmprieur** [comment]
Thanks for checking, @Eldin66 
On my side I've tested on UWP and this works like on Android.
I've changed the title of this issue to "Token cache is not persisted on iOS". Feel free to rename if you disagree.
I'll raise an issue in MSAL.NET

**Comment by jmprieur** [comment]
Which version of MSAL are you using, @Eldin66 ?

**Comment by Eldin66** [comment]
I use 1.1.2-preview0008. 
For now the title reflects the problem correctly! That could change if it runs correctly on a real device though.

**Comment by jmprieur** [comment]
@Eldin66 were you able to check if it runs an a real device?
@jennyf19 did we investigate this issue?

**Comment by jennyf19** [comment]
@jmprieur @Eldin66 - there is a known issue w/iOS simulator. This should work fine on a device. I will need to get more details from the iOS team.

**Comment by jennyf19** [comment]
Using the sample and iPhone SE 11.3 simulator, I was able to:
> Hit Sign-In (entered username, password)
> Hit Sign-Out
> Hit Sign-In -> Asked to "Pick an Account" 
> Picked account and was logged in (not prompted to enter password again)
> Closed the simulator and restarted
> Hit Sign-in -> Asked to "Pick an Account"
> Picked account and was logged in (not prompted to enter password again)

Based on this analysis, the cache on simulator appears to be working as expected. According to iOS team, simulator does not use keychain sharing group, but a device will use keychain. But our MSAL cache is working as expected.

@Eldin66 - Can you give more details into your issue and what you are experiencing? Thanks.

@jmprieur

**Comment by MathildeRoussel** [comment]
Hello,

I've just tested this sample on an iOS simulator (iPhone X 11.3), the AcquireTokenSilentAsync works fine, only you have to specify in your provisioning profile that you want to use the Keychain, and then add in the Entitlements.plist a new key for keychain-access-group with your app bundle id.

After that I'm able to first log in with my password, and when I restart the app I'm already logged in (no need to click on "sign in" and to pick an account)

IMHO there is no bug, you can close this issue and also that one : https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/546

**Comment by jmprieur** [comment]
Closing this issue as @MathildeRoussel added missing steps in the iOS specific considerations

**Comment by ajaysbsic** [comment]
@MathildeRoussel  @jmprieur  Hi, I am working in xamarin forms App (ADAL) and new in iOS please can you suggest me how exactly we can specify in our provisioning profile that we want to use the Keychain ?

**Comment by jennyf19** [comment]
@ajaysbsic I suggest you try [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal). Here is information on [iOS specifics](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities) with MSAL. Let us know how we can help.

**Comment by ajaysbsic** [comment]
@jennyf19  Thanks a ton , this is what I was looking for.

**Comment by jennyf19** [comment]
@ajaysbsic can you tell us more about what you need in ADAL that you can't get from MSAL? thank you.

cc: @jmprieur

**Comment by ajaysbsic** [comment]
@jennyf19  Sorry , I was just confused with MathildeRoussel comment "the AcquireTokenSilentAsync works fine, only you have to specify in your provisioning profile that you want to use the Keychain" so I was wondering if I need to do something in my Provisioning profile, to get the cached Token working.
actually I was always getting an exception "AdalError.FailedToAcquireTokenSilently",  everytime  when I restart the app.
Thanks to you , I just go through this link :: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities, and followed these steps : 
1. Enable Keychain access in your Entitlements.plist file and specify in the Keychain Groups your bundle identifier.
2. In your project options, on iOS Bundle Signing view, select your Entitlements.plist file for the Custom Entitlements field.
3. When signing a certificate, make sure XCode uses the same Apple Id.
and now I am able to get the cache Token.

Thanks, please let me know if I missed or ignored anything.

**Comment by jennyf19** [comment]
@ajaysbsic Sounds like you got things working! Glad the link helped. Let us know if you need anything else.
