### ISSUE TITLE
Crashes when offline

### ISSUE THREAD

**Issue by Surfrat** [Azure-Samples/active-directory-xamarin-native-v2#26]
When I run this offline this is what happens:
![image](https://user-images.githubusercontent.com/2066487/39571493-ed1d0406-4ecb-11e8-8b58-7db10cd1fd86.png)

Your v1 of this project had a problem in that it would not work offline unless a web api was defined. I was hoping this would have fixed that.

Thanks

Surfrat.

**Comment by jmprieur** [comment]
@Surfrat 
what do you mean offline? you mean disconnected from the network? 
Considering that the sample calls the Microsoft Graph which is an online service, I don't know how this could work offline. please elaborate

**Comment by Surfrat** [comment]
So how would I use this in a mobile app that is offline? Your previous sample v1 works this way. I thought the whole point of Azure Active Directory B2C was to provide credential management in an offline and connected way. Am I missing something here ?

**Comment by jmprieur** [comment]
I see what you mean.
this is not an Azure AD B2C sample but an Azure AD. Azure AD is an identity provider (identity as a service) in the cloud. The -v2 does not mean that this is a V2 version of a sample, but the V2 version of the Azure AD protocol. See [Choosing between ADAL.NET (Azure AD V1) and MSAL.NET (Azure AD V2)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Register-your-application-with-Azure-Active-Directory#choosing-between-adalnet-azure-ad-v1-and-msalnet-azure-ad-v2)

The B2C sample is available from: [Azure-Samples/active-directory-b2c-xamarin-native](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native)

**Comment by Surfrat** [comment]
Thanks for the explanation. Makes sense :)
