### ISSUE TITLE
Xamarin.Mac AuthenticationContinuationHelper missing

### ISSUE THREAD

**Issue by matszafraniec** [Azure-Samples/active-directory-xamarin-native-v2#29]
Hi,

Is there any way to implement this solution for Xamarin**.Mac** project? After install Microsoft.Identity.Client package VS cannot see AuthenticationContinuationHelper class.

Regards
Mateusz

**Comment by jmprieur** [comment]
No, @matszafraniec we don't support Xamarin.Mac yet.
How important is it for your business?
