### ISSUE TITLE
iOS SignIn"Safari cannot open the page because the address is invalid"

### ISSUE THREAD

**Issue by MartinOpde** [Azure-Samples/active-directory-xamarin-native-v2#31]
There is an error in the iOS sample using de default values.

in info.plist : 
```
<key>CFBundleURLSchemes</key>
<array>
	<string>msal7d8cef0-4145-49b2-a91d-95c54051fa3f</string>
</array>
```

msal7d8cef0-4145-49b2-a91d-95c54051fa3f

should be

msala7d8cef0-4145-49b2-a91d-95c54051fa3f

**Comment by jmprieur** [comment]
Thanks for the heads-up, @MartinOpde : this is now fixed
cc: @jennyf19
