### ISSUE TITLE
Microsoft.Identity.Client 1.1.4.0: UIParent missing constructor UIParent(Activity activity)

### ISSUE THREAD

**Issue by jpdc-developer** [Azure-Samples/active-directory-xamarin-native-v2#32]
I've installed `Microsoft.Identity.Client, Version=1.1.4.0`  and have downloaded the [sample application](https://github.com/Azure-Samples/active-directory-xamarin-native-v2). I am trying to make the Xamarin solution that is as similar as possible to the sample application.

They both have the same version of  `Microsoft.Identity.Client` but when expanding the region above the UIParent Class, the sample application uses `monoandroid81 `while our app uses `netstandard1.3`.

How can I use the UIParent with the signature: `public UIParent(Activity activity)`?
I'm guessing to make my solution have a similar structure, I have to change the project from using `netstandard1.3` to  `monoandroid81`. How would I go about doing this?

**Comment by robintschroeder** [comment]
Drop back to 1.1.2-preview0008

**Comment by jmprieur** [comment]
Hello @jpdc-developer 
I've just tried the sample and it worked fine for me. 
Yes, if you have an Android 8.1 application, you should change the target. 
Closing for now, but feel free to reopen, providing repro steps if you still see an issue.
