### ISSUE TITLE
never look into tokencache

### ISSUE THREAD

**Issue by cherici-simone** [Azure-Samples/active-directory-xamarin-native-v2#37]
I'm creation a Xamarin.forms app using B2C AD; I update to version 2.0.0 and change my code to use IAccount and not IUser but now I have a couple of errors (one in iOS) and the other in Android.
On iOS I receive a object not reference not set exception during login while in Android it seems that TokenCache if never used and every time I have to login again

**Comment by jmprieur** [comment]
Thanks for reporting, @cherici-simone 
This is one of the known issues: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#known-issues

MSAL 2.0.0-preview's cache has a bug with B2C. we are working on it (See [MSAL.NET #604](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/604))

**Comment by jmprieur** [comment]
cc: @henrik-me @jennyf19 @trwalke

**Comment by jmprieur** [comment]
See also https://aka.ms/msal-net-token-cache-index-keys

**Comment by bgavrilMS** [comment]
@cherici-simone - this has been fixed in MSAL 2.0.1 - Please reopen the issue if you still encounter problems.
