### ISSUE TITLE
NullReferenceException in iOS only

### ISSUE THREAD

**Issue by ali-h2010** [Azure-Samples/active-directory-xamarin-native-v2#39]
I am getting a runtime error:
`System.NullReferenceException: Object reference not set to an instance of an object`
When i click on Sign in button.
the error is occurring at this step (PCA is null):

```
PCA = new PublicClientApplication(ClientID)
                {
                    RedirectUri = $"msal{App.ClientID}://auth",
                };  
``` 

Complete Error:

`    
    System.NullReferenceException: Object reference not set to an instance of an object
    at Microsoft.Identity.Core.TokenCacheAccessor.GetTeamId () [0x0003f] in <772466974f16475694ca93a5f7a70108>:0
    at Microsoft.Identity.Core.TokenCacheAccessor..ctor () [0x0001c] in <772466974f16475694ca93a5f7a70108>:0
    at Microsoft.Identity.Core.Telemetry.TelemetryTokenCacheAccessor..ctor () [0x00000] in <772466974f16475694ca93a5f7a70108>:0 
    at Microsoft.Identity.Client.TokenCache..ctor () [0x00000] in <772466974f16475694ca93a5f7a70108>:0 
    at Microsoft.Identity.Client.PublicClientApplication..ctor (System.String clientId, System.String authority) [0x00014] in <772466974f16475694ca93a5f7a70108>:0 
    at Microsoft.Identity.Client.PublicClientApplication..ctor (System.String clientId) [0x00000] in <772466974f16475694ca93a5f7a70108>:0 
    at UserDetailsClient.App..ctor () [0x00009] in Downloads/active-directory-xamarin-native-v2-master/UserDetailsClient/UserDetailsClient/App.cs:30 `

Only iOS is giving me this . Android Version is working fine.
I am using Visual Studio for Mac

**Comment by jmprieur** [comment]
Thanks for reporting @ali-h2010 
This looks like the same as https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/611


Are you running it on the simulator? or an actual device? 
Also did you have a previous version of the application (using MSAL.NET 1.1.4-preview) already installed ?

cc: @jennyf19

**Comment by ali-h2010** [comment]
Thanks for your reply @jmprieur.
Yes, i am running on an iphone simulator. I will try an actual device and see if the behavior is the same or not.

I didn't have any old version installed before.

We can remove this issue and continue on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/611 , since it was created one hour before me. 

Regards
Ali

**Comment by sergioacortes** [comment]
Same problem, I have tested it with emulator and physical device, I have downgrade to version 1.1.4 preview and it works. 

Guess it is a problem within the constructor of PublicClientApplication class

Regards

**Comment by ali-h2010** [comment]
@sergioacortes 
But version 1.1.4 does not store the session for me. There are no users stored in PCA 
I can't access current logged in users or sign out.

**Comment by sergioacortes** [comment]
I have downgrade, it works on iOs emulator but no physical device.

**Comment by sergioacortes** [comment]
Update: version 1.1.4 works with physical devices with iOs under version 12

**Comment by tipa** [comment]
The same issue occurs for me when the auth is attempted while the phone screen is locked. Then the library cannot access the keychain and get the teamId, resulting in the error. Maybe adding `Accessible = SecAccessible.Always` to this line resolves the issue: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/1d3eb8c49be9039d99c1bf0057e98506c256b6de/core/src/Platforms/iOS/TokenCacheAccessor.cs#L89

**Comment by tipa** [comment]
I was able to worked around the issue with the following hack:
```
var whenUnlockedAccessRecord = new SecRecord(SecKind.GenericPassword) { Service = "", Account = "teamIDHint" };
var match = SecKeyChain.QueryAsRecord(whenUnlockedAccessRecord, out SecStatusCode resultCode);
if (resultCode == SecStatusCode.Success && match.Accessible != SecAccessible.Always)
{
    SecKeyChain.Remove(whenUnlockedAccessRecord);
}

if (match?.Accessible != SecAccessible.Always)
{
    var alwaysAccessRecord = new SecRecord(SecKind.GenericPassword) { Service = "", Account = "teamIDHint", Accessible = SecAccessible.Always };
    SecKeyChain.Add(alwaysAccessRecord);
}
```

Speaking of hack: I must say that the `GetTeamId()` method looks pretty hacky too :P

**Comment by jennyf19** [comment]
This has been fixed in this sample. Can one of you confirm the sample works for you now on iOS? Thanks!
@tipa @sergioacortes @ali-h2010

**Comment by ali-h2010** [comment]
@jennyf19 , Thanks for the update and support. Will Test soon.

**Comment by sergioacortes** [comment]
Thanks, I'll test it soon

**Comment by ali-h2010** [comment]
@jennyf19 
I tested and it works out of the box as expected. 
Great work

**Comment by jennyf19** [comment]
@ali-h2010 @sergioacortes @tipa 
returning error message in [MSAL v2.2.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.2.0)  and updates to [wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities#enable-keychain-access) for configuration assistance

Please re-open if you continue to have issues w/this. Thanks for all your help!
