### ISSUE TITLE
Xamarin/UWP - AAD B2C compatible library

### ISSUE THREAD

**Issue by punitganshani** [Azure-Samples/active-directory-xamarin-native-v2#4]
As per the article below, MSAL should not be used for production. 
Is there any other alternative for `AAD B2C` that can be used for production?

`
https://azure.microsoft.com/en-us/resources/samples/active-directory-b2c-xamarin-native/
`

**Comment by danieldobalian** [comment]
@punitganshani as of Build 2017, MSAL .NET is suitable and supported for production environments; however, the library is still in preview and is subject to major changes and expectation to update to GA when available.  

Read more here (Heading: Important Note about the MSAL Preview): https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
