### ISSUE TITLE
Skip Microsoft login page and Taking you to your organization's sign-in page

### ISSUE THREAD

**Issue by ali-h2010** [Azure-Samples/active-directory-xamarin-native-v2#41]
In Xamarin forms, we require to authenticate our employees only into the app. 
So, we need to redirect the user directly to our organization's sign-in page.

I am not sure where to assign this value. Could it be in the Redirect URI?
`RedirectUri = $"msal{App.ClientID}://auth",`

Would this work if we create an app id and pass it here?

**Comment by ali-h2010** [comment]
From my research i found out that i need to add a domain hint to Azure home Realm in order to redirect to work sign in page. The issue is that, i can't find any documentation on how to add this hint.

Kindly support me with this issue

**Comment by ali-h2010** [comment]
I found out the solution
AcquireTokenAsync(App.Scopes,"someone@domain.com" ,App.UiParent);

**Comment by bgavrilMS** [comment]
Thank you for posting the answer @ali-h2010 !
