### ISSUE TITLE
Cannot authenticate apps created on Azure Free tier

### ISSUE THREAD

**Issue by Katydude** [Azure-Samples/active-directory-xamarin-native-v2#50]
I was able to successfully authenticate an application on the Android platform (SDK 25) in my Premium P1 subscription. However, when I created an application in my free Azure AD portal and switched out the GUIDs, the authentication flow breaks after I enter my username, choose Personal for the realm, and enter my known good password. The error page that is presented in Chrome has login.live.com as the URL and the simple "We're unable to complete your request. Microsoft account is experiencing technical problems. Please try again later."

I tried manually setting the authority in the App.cs file to each of https://login.microsoftonline.com/tenant/, https://login.microsoftonline.com/mailnew.....microsoftonline.com/ (which is my AD tenant name), https://login.microsoftonline.com/consumers/, and https://login.microsoftonline.com/corporate/. None of these worked and all resulted in the same error message. Can you offer guidance on the changes that need to be made, other than the App Id, in order to support Azure Free AD tier? 

[Edit: More info] Let me throw this in. I decided to create an additional user in my AD. After saving, I notice that the new user is labeled (in the Source column) as an Azure Active Directory account. My administrative account is listed as a Microsoft Account. This seems odd if they are in the same AD. I will add this: I was one of the first to sign up for a free Azure developer account several years ago. I receive an Office 365 Enterprise E3 Developer MSDN billing statement every month. Could my account be sort of an oddball account? Thanks!

**Comment by Katydude** [comment]
Oh, one last comment. I switched to a new, free Azure AD account and tried again. On this account, I have two-factor authentication turned on. It does not allow me to log in on this AD, either.

**Comment by Katydude** [comment]
Alright, I guess there will be yet another comment. When comparing the manifest of a working application to the on on my E3 Developer account, the schema is completely different. It does not allow me to set a value for signInAudience. This is the key difference in getting the application to authenticate. I created a new, Free AD account and made an application. In doing so, it let me toggle the  Supported Account Types between AD only, multiple ADs and ADs with Public accounts. When I chose this last one, I could authenticate. When I switched back to my E3 account, I could not go into the manifest and change the value to AzureADandPersonalMicrosoftAccount because the schema doesn't include a space for it.

Sounds like there are just some key differences between all of the different flavors of Azure running out there.

**Comment by jmprieur** [comment]
@Katydude : how did you create your application in your free Azure AD portal?. Did you make sure your used the new **App Registration (Preview)** tab in the Active Directory Service in https://portal.azure.com? you might not see it in all subscriptions yet as it's being deployed, but if you don't this will come soon.. It replaces https://apps.dev.microsoft.com, and these two are the only way to create applications with the Microsoft Personal Account audience.

**Comment by Katydude** [comment]
Yes, I created it that way to the best of my knowledge but I think if you choose AD Only at first, the manifest gets the reduced schema. Anyway, ultimately that was the issue. Thanks for the response. This library seems to work great, by the way :+1:
