### ISSUE TITLE
code sample throws an error for Xamarin.iOS project

### ISSUE THREAD

**Issue by Gold14388** [Azure-Samples/active-directory-xamarin-native-v2#59]
When I try to run the code sample project locally, I get the below-mentioned error.
**_Severity	Description	Project	File	Line	Suppression State
Error	Can't resolve the reference 'System.String System.String::TrimStart(System.Char)', referenced from the method 'Microsoft.Identity.Json.Schema.JsonSchema Microsoft.Identity.Json.Schema.JsonSchemaBuilder::ResolveReferences(Microsoft.Identity.Json.Schema.JsonSchema)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.	UserDetailsClient.iOS_**			

I am using Visual Studio Professional 2017 version 15.8.6

**Comment by jmprieur** [comment]
@Gold14388 
This is a well known issue with Xamarin: you need to update Visual Studio to 15.9.4

For details see:
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/752 or 
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/745. 

proposing to close as it's answered. Feel free to reopen if this does not work for you.

**Comment by Gold14388** [comment]
@jmprieur , Thanks for directing me towards the solution but after updating Visual Studio, When I try to run the UserDetailsClient.iOS project it gives me another error
**_Severity	Description	Project	File	Line	Suppression State
Error	Your application is using the 'AuthenticationServices' framework, which isn't included in the iOS SDK you're using to build your app (this framework was introduced in iOS 12.0, while you're building with the iOS 11.4 SDK.) Please select a newer SDK in your app's iOS Build options.	UserDetailsClient.iOS_**

**Comment by jmprieur** [comment]
@trwalke @jennyf19 : can you please help?

**Comment by trwalke** [comment]
for the AuthenticationServices to build properly you need to not only be on the latest Visual studio but also target the latest iOS SDK. AuthenticationServices was introduced in iOS 12 so you must use the iOS 12 SDK and above. if you are on windows, try updating XCode on the remote mac agent that you connect to for building.
