### ISSUE TITLE
building project UserDetailsClient.iOS  throws iOS sdk version error

### ISSUE THREAD

**Issue by Gold14388** [Azure-Samples/active-directory-xamarin-native-v2#60]
Whenever I try to run the project, I get below-mentioned error.

**_Severity	Description	Project	File	Line	Suppression State
Error	Your application is using the 'AuthenticationServices' framework, which isn't included in the iOS SDK you're using to build your app (this framework was introduced in iOS 12.0, while you're building with the iOS 11.4 SDK.) Please select a newer SDK in your app's iOS Build options.	UserDetailsClient.iOS_**

**Comment by jennyf19** [comment]
@Gold14388 You need to use the latest version of Visual Studio and also target the latest iOS SDK. AuthenticationServices was introduced in iOS 12, so you must use the iOS 12 SDK and above. If you are on windows, try updating XCode on the remote mac agent.

**Comment by jennyf19** [comment]
@Gold14388 Going to close, as doing the above should resolve the issue. Please reopen if necessary. Thanks.
