### ISSUE TITLE
Master-Detail Xamarin Application starts empty MainPage in iOS and Android

### ISSUE THREAD

**Issue by Orgbrat** [Azure-Samples/active-directory-xamarin-native-v2#71]
I used your guide to add MSAL to my Xamarin forms app. I followed your guide first and got your sample app working and it worked great in all projects (iOS, Droid and UWP). But when I converted my application which happens to be a Master-Detail Xamarin application, I thought all was fine when I tested UWP first and it worked great. But when I tried iOS and Droid the application started but all I got was a blank MainPage. I think this has something to do with the MainPageRenderer in the iOS and Droid projects. Although I am not sure what needs to be fixed to make a MasterDetail Xamarin application work correctly. I have a sample that I built using the VS 2019 default Xamarin Forms MasterDetail project and added what it needed for MSAL from your project. It fails to display MainPage just like my application. I cleaned out my test project of all obj and Debug folders so it would upload for your inspection. I have spent several days trying to make this work without success. Can you assist me with this issue?

Steve
[TestMasterDetail.zip](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/files/3194711/TestMasterDetail.zip)

**Comment by Orgbrat** [comment]
Well I think I have it working! I have published my Test project to a public Github repository for evaluation.
[OneDrive-MasterDetail on Github](https://github.com/Orgbrat/OneDrive-MasterDetail)

Orgbrat

**Comment by jmprieur** [comment]
+ @bgavrilMS FYI

**Comment by jennyf19** [comment]
@Orgbrat looks like you have resolved the issue...going to close, but please reopen if you are still encountering issues.
