### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by xammob** [Azure-Samples/active-directory-xamarin-native-v2#8]
Is there anyway for the security token to be persisted (refresh token?) so that when the app closes and re-opens again, the user doesn't have to keep re-entering their credentials?

**Comment by krishnahitachi** [comment]
When the application is re-launched it is not persisting previously logged in user.  how to make the user persist when application is re-launched? 

The following exception is throwing while trying to acquire token silently when application is re-launched.

 {Microsoft.Identity.Client.MsalUiRequiredException: Null user was passed in AcquiretokenSilent API. Pass in a user object or call acquireToken authenticate.

Is there anyway to handle it?

**Comment by TNoronha** [comment]
You can handle it like so @krishnahitachi :

`
AuthenticationResult ar;
try
            {
                ar = await App.ClientApplication.AcquireTokenSilentAsync(App.Scopes, App.ClientApplication.Users.FirstOrDefault());
            }
            catch (MsalUiRequiredException ex)
            {
                //No token found.
                ar = await App.ClientApplication.AcquireTokenAsync(App.Scopes, App.UiParent);
            }
`

**Comment by jmprieur** [comment]
Closing as this does not repro any longer (we call App.PCA.Users.FirstOrDefault() in MainPage.xaml.cs in the UserDetailsClient project.
