### ISSUE TITLE
Rename master branch to msal2x, and msal3x branch to master

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-xamarin-native-v2#94]
### Why?
The default branch for this sample is msal3x
and the master branch is featuring msal2x
this is confusing for customers (and maintainers)

### Impact: 
no impact on the quickstart as there is no quickstart yet for this scenario

### What?
We want to:
- rename the current `master` branch to `msal2x`
- rename the current `msal3x` to `master`
- set the default branch of the repository to be `master`

cc: @jennyf19 @henrik-me @trwalke @bgavrilMS

**Comment by jmprieur** [comment]
### Why?
The default branch for this sample is msal3x
and the master branch is featuring msal2x
this is confusing for customers (and maintainers)

### Impact: 
no impact on the quickstart as there is no quickstart yet for this scenario

### What?
We want to:
- rename the current master branch to msal2x
- rename the current msal3x to master

cc: @jennyf19 @henrik-me @trwalke @bgavrilMS

**Comment by jmprieur** [comment]
Done
Note that the default branch is now master

**Comment by jennyf19** [comment]
@jmprieur awesome! thanks again. #PMMagic

**Comment by jmprieur** [comment]
Merci Jenny!!!
