### ISSUE TITLE
Transform the repository into a multi-step tutorial

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-xamarin-native-v2#95]
### Why?
Now that Xamarin.iOS supports the broker (authenticator), and with the support of broker to Xamarin.Android coming, we want to transform this sample into a multi-step tutorial featuring:
- without broker
- with Authenticator (for iOS for the moment)
- with the mobile app calling its own web API (later)

### What?
- Move AppCreationScripts, ReadmeFiles, UserDetailsClient, the solution, and the README.md to a sub-folder named "1-Basic"
- Create another folder "2-With-broker" with the current content of https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/jennyf/iosBroker, and the README.md from https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/jennyf/ios/XamarinBroker/UserDetailsClientBroker/README.md.
  > Note that the app creation scripts might not work so well as the replyUri are different
- Create a master README.md in the root of the repository, explaning the two steps.

cc: @jennyf19

**Comment by jennyf19** [comment]
wow... @jmprieur thank you so much! merci! this is wonderful. ☃️
